import { Device, DeviceStatus, DeviceType, Vendor, Alert, MetricPoint, Company } from './types';

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'c1',
    name: 'Condomínio Jardins (Cliente A)',
    document: '12.345.678/0001-90',
    status: 'WARNING',
    agentStatus: 'CONNECTED',
    agentIp: '200.10.10.5',
    totalDevices: 12,
    contact: 'Síndico João',
  },
  {
    id: 'c2',
    name: 'Logística Express (Cliente B)',
    document: '98.765.432/0001-10',
    status: 'HEALTHY',
    agentStatus: 'CONNECTED',
    agentIp: '189.50.20.1',
    totalDevices: 45,
    contact: 'Gerente TI Ana',
  },
  {
    id: 'c3',
    name: 'Supermercado Popular (Cliente C)',
    document: '11.111.222/0001-33',
    status: 'CRITICAL',
    agentStatus: 'DISCONNECTED',
    agentIp: 'Unknown',
    totalDevices: 8,
    contact: 'Gerente Marcos',
  },
];

export const MOCK_DEVICES: Device[] = [
  // Empresa C1
  {
    id: '1',
    companyId: 'c1',
    name: 'Câmera Entrada Principal',
    ip: '192.168.1.101',
    port: 80,
    type: DeviceType.CAMERA,
    vendor: Vendor.INTELBRAS,
    model: 'VIP 3230 B',
    location: 'Portão A',
    status: DeviceStatus.ONLINE,
    uptime: '14d 2h 12m',
    lastSeen: 'Agora mesmo',
    firmware: '2.4.1',
    mac: 'AA:BB:CC:DD:EE:01',
    tags: ['externa', 'entrada'],
  },
  {
    id: '2',
    companyId: 'c1',
    name: 'PTZ Galpão',
    ip: '192.168.1.102',
    port: 80,
    type: DeviceType.CAMERA,
    vendor: Vendor.INTELBRAS,
    model: 'VIP 5220 SD',
    location: 'Galpão B',
    status: DeviceStatus.WARNING,
    uptime: '2d 5h 0m',
    lastSeen: '1 min atrás',
    firmware: '1.0.0',
    mac: 'AA:BB:CC:DD:EE:02',
    tags: ['ptz', 'estoque'],
  },
  // Empresa C2
  {
    id: '3',
    companyId: 'c2',
    name: 'NVR Central',
    ip: '10.0.0.200',
    port: 37777,
    type: DeviceType.NVR,
    vendor: Vendor.INTELBRAS,
    model: 'MHDX 3116',
    location: 'Sala de Servidores',
    status: DeviceStatus.ONLINE,
    uptime: '45d 10h 33m',
    lastSeen: 'Agora mesmo',
    firmware: '4.000.00IB0',
    mac: 'AA:BB:CC:DD:EE:03',
    tags: ['gravador', 'core'],
  },
  // Empresa C3 (Offline/Critical)
  {
    id: '4',
    companyId: 'c3',
    name: 'Sensor Perímetro',
    ip: '192.168.0.150',
    port: 80,
    type: DeviceType.ALARM,
    vendor: Vendor.GENERIC,
    model: 'AMT-8000 Bridge',
    location: 'Cerca Perímetro',
    status: DeviceStatus.OFFLINE,
    uptime: '0m',
    lastSeen: '2 horas atrás',
    firmware: 'v1.2',
    mac: 'AA:BB:CC:DD:EE:04',
    tags: ['segurança', 'perímetro'],
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'a1',
    companyId: 'c3',
    deviceId: '4',
    deviceName: 'Sensor Perímetro',
    severity: 'CRITICAL',
    message: 'Dispositivo Inacessível (Agente desconectado)',
    timestamp: '27/10/2023 14:30:00',
    acknowledged: false,
  },
  {
    id: 'a2',
    companyId: 'c1',
    deviceId: '2',
    deviceName: 'PTZ Galpão',
    severity: 'HIGH',
    message: 'Alta Latência Stream RTSP (>500ms)',
    timestamp: '27/10/2023 14:15:00',
    acknowledged: false,
  },
  {
    id: 'a3',
    companyId: 'c2',
    deviceId: '3',
    deviceName: 'NVR Central',
    severity: 'LOW',
    message: 'Uso de Armazenamento > 85%',
    timestamp: '27/10/2023 10:00:00',
    acknowledged: true,
  },
];

export const BITRATE_DATA: MetricPoint[] = [
  { time: '10:00', value: 4500 },
  { time: '10:05', value: 4200 },
  { time: '10:10', value: 4800 },
  { time: '10:15', value: 5100 },
  { time: '10:20', value: 2000 },
  { time: '10:25', value: 4600 },
  { time: '10:30', value: 4700 },
];

export const NETWORK_TRAFFIC_DATA: MetricPoint[] = [
  { time: '10:00', value: 120 },
  { time: '10:05', value: 135 },
  { time: '10:10', value: 125 },
  { time: '10:15', value: 180 },
  { time: '10:20', value: 150 },
  { time: '10:25', value: 140 },
  { time: '10:30', value: 160 },
];
